"""init

Revision ID: c5698358ca05
Revises: 
Create Date: 2017-07-22 22:40:07.230505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5698358ca05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('modified_at', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.String(length=64000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('comments_domain_id', 'comments', ['domain_id'], unique=False)
    op.create_index('comments_domain_id_modified_at', 'comments', ['domain_id', 'modified_at'], unique=False)
    op.create_index('comments_name_type', 'comments', ['name', 'type'], unique=False)
    op.create_index(op.f('ix_comments_domain_id'), 'comments', ['domain_id'], unique=False)
    op.create_index(op.f('ix_comments_modified_at'), 'comments', ['modified_at'], unique=False)
    op.create_index(op.f('ix_comments_name'), 'comments', ['name'], unique=False)
    op.create_index(op.f('ix_comments_type'), 'comments', ['type'], unique=False)
    op.create_table('cryptokeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('cryptokeys_domain_id', 'cryptokeys', ['domain_id'], unique=False)
    op.create_table('domainmetadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('domainmetadata_domain_id_kind', 'domainmetadata', ['domain_id', 'kind'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('master', sa.String(length=255), nullable=True),
    sa.Column('last_check', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('notified_serial', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('domains_name', 'domains', ['name'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=6), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('prio', sa.Integer(), nullable=True),
    sa.Column('change_date', sa.Integer(), nullable=True),
    sa.Column('disabled', sa.SmallInteger(), nullable=False),
    sa.Column('ordername', sa.String(length=255), nullable=True),
    sa.Column('auth', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('records_domain_id', 'records', ['domain_id'], unique=False)
    op.create_index('records_domain_id_ordername', 'records', ['domain_id', 'ordername'], unique=False)
    op.create_index('records_name_type', 'records', ['name', 'type'], unique=False)
    op.create_table('supermasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('nameserver', sa.String(length=255), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', 'ip', 'nameserver'),
    mysql_engine='InnoDB'
    )
    op.create_table('tsigkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index('tsigkeys_name_algorithm', 'tsigkeys', ['name', 'algorithm'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tsigkeys_name_algorithm', table_name='tsigkeys')
    op.drop_table('tsigkeys')
    op.drop_table('supermasters')
    op.drop_index('records_name_type', table_name='records')
    op.drop_index('records_domain_id_ordername', table_name='records')
    op.drop_index('records_domain_id', table_name='records')
    op.drop_table('records')
    op.drop_index('domains_name', table_name='domains')
    op.drop_table('domains')
    op.drop_index('domainmetadata_domain_id_kind', table_name='domainmetadata')
    op.drop_table('domainmetadata')
    op.drop_index('cryptokeys_domain_id', table_name='cryptokeys')
    op.drop_table('cryptokeys')
    op.drop_index(op.f('ix_comments_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_name'), table_name='comments')
    op.drop_index(op.f('ix_comments_modified_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_domain_id'), table_name='comments')
    op.drop_index('comments_name_type', table_name='comments')
    op.drop_index('comments_domain_id_modified_at', table_name='comments')
    op.drop_index('comments_domain_id', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
