"""mod task

Revision ID: 1c58ee1dd1c6
Revises: 86fbdb065fb4
Create Date: 2016-05-21 19:01:29.631168

"""

# revision identifiers, used by Alembic.
revision = '1c58ee1dd1c6'
down_revision = '86fbdb065fb4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('pallalel', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('target', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'target')
    op.drop_column('task', 'pallalel')
    ### end Alembic commands ###
