"""empty message

Revision ID: 30504c2b230a
Revises: 1833dfb280f4
Create Date: 2016-04-10 12:44:14.130322

"""

# revision identifiers, used by Alembic.
revision = '30504c2b230a'
down_revision = '1833dfb280f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('hooked', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'hooked')
    ### end Alembic commands ###
