"""init

Revision ID: 3309b47f3848
Revises: c9ba87da0638
Create Date: 2016-09-24 22:10:21.244073

"""

# revision identifiers, used by Alembic.
revision = '3309b47f3848'
down_revision = 'c9ba87da0638'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent', 'check_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('agent', 'check_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('agent', 'setup_status',
               existing_type=mysql.VARCHAR(length=55),
               nullable=True)
    op.alter_column('agent', 'setup_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent', 'setup_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('agent', 'setup_status',
               existing_type=mysql.VARCHAR(length=55),
               nullable=False)
    op.alter_column('agent', 'check_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('agent', 'check_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
