"""mod task

Revision ID: 541071568ae6
Revises: 1c58ee1dd1c6
Create Date: 2016-05-21 19:03:04.421438

"""

# revision identifiers, used by Alembic.
revision = '541071568ae6'
down_revision = '1c58ee1dd1c6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
