"""empty message

Revision ID: 64f8363d72d6
Revises: ef338fa9777a
Create Date: 2016-04-03 11:19:39.729359

"""

# revision identifiers, used by Alembic.
revision = '64f8363d72d6'
down_revision = 'ef338fa9777a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('status', sa.String(length=55), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'status')
    ### end Alembic commands ###
