"""mod task

Revision ID: 6e8be522a11b
Revises: 913114c4f8a7
Create Date: 2016-05-21 22:06:55.579425

"""

# revision identifiers, used by Alembic.
revision = '6e8be522a11b'
down_revision = '913114c4f8a7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
