"""empty message

Revision ID: 83d49cc94915
Revises: 30504c2b230a
Create Date: 2016-04-29 12:13:28.651278

"""

# revision identifiers, used by Alembic.
revision = '83d49cc94915'
down_revision = '30504c2b230a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('check_timestamp', sa.DateTime(), nullable=False))
    op.drop_column('agent', 'heartbeat_timestamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('heartbeat_timestamp', mysql.DATETIME(), nullable=False))
    op.drop_column('agent', 'check_timestamp')
    ### end Alembic commands ###
