"""add task

Revision ID: 86fbdb065fb4
Revises: cd814a3f704d
Create Date: 2016-05-21 18:52:01.709472

"""

# revision identifiers, used by Alembic.
revision = '86fbdb065fb4'
down_revision = 'cd814a3f704d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('json_arg', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('err_msg', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    ### end Alembic commands ###
