"""empty message

Revision ID: c7f8b9624381
Revises: 64f8363d72d6
Create Date: 2016-04-03 11:52:34.122648

"""

# revision identifiers, used by Alembic.
revision = 'c7f8b9624381'
down_revision = '64f8363d72d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('err_status', sa.String(length=55), nullable=False))
    op.add_column('agent', sa.Column('last_crit_errs', sa.String(length=255), nullable=False))
    op.add_column('agent', sa.Column('last_crit_total_errs', sa.Integer(), nullable=False))
    op.add_column('agent', sa.Column('last_warn_errs', sa.String(length=255), nullable=False))
    op.add_column('agent', sa.Column('last_warn_total_errs', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'last_warn_total_errs')
    op.drop_column('agent', 'last_warn_errs')
    op.drop_column('agent', 'last_crit_total_errs')
    op.drop_column('agent', 'last_crit_errs')
    op.drop_column('agent', 'err_status')
    ### end Alembic commands ###
