"""init

Revision ID: c9ba87da0638
Revises: 
Create Date: 2016-09-24 20:18:28.207281

"""

# revision identifiers, used by Alembic.
revision = 'c9ba87da0638'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_type', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('check_status', sa.Integer(), nullable=False),
    sa.Column('check_timestamp', sa.DateTime(), nullable=False),
    sa.Column('setup_status', sa.String(length=55), nullable=False),
    sa.Column('setup_timestamp', sa.DateTime(), nullable=False),
    sa.Column('fabscript_map', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('fabscript', sa.String(length=255), nullable=False),
    sa.Column('msg', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('hooked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('json_arg', sa.String(length=500), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('pallalel', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('err_msg', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('event')
    op.drop_table('agent')
    ### end Alembic commands ###
