"""init

Revision ID: cd814a3f704d
Revises: 
Create Date: 2016-05-05 21:59:56.125430

"""

# revision identifiers, used by Alembic.
revision = 'cd814a3f704d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_type', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('check_status', sa.Integer(), nullable=False),
    sa.Column('check_timestamp', sa.DateTime(), nullable=False),
    sa.Column('setup_status', sa.String(length=55), nullable=False),
    sa.Column('setup_timestamp', sa.DateTime(), nullable=False),
    sa.Column('fabscript_map', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('fabscript', sa.String(length=255), nullable=False),
    sa.Column('msg', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('hooked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('agent')
    ### end Alembic commands ###
