"""empty message

Revision ID: d3e764a1db46
Revises: d511790fa384
Create Date: 2016-04-09 23:10:55.662233

"""

# revision identifiers, used by Alembic.
revision = 'd3e764a1db46'
down_revision = 'd511790fa384'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('check_status', sa.Integer(), nullable=False))
    op.add_column('agent', sa.Column('setup_result', sa.String(length=255), nullable=False))
    op.add_column('agent', sa.Column('setup_status', sa.String(length=55), nullable=False))
    op.add_column('agent', sa.Column('setup_timestamp', sa.DateTime(), nullable=False))
    op.drop_column('agent', 'err_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('err_status', mysql.VARCHAR(length=55), nullable=False))
    op.drop_column('agent', 'setup_timestamp')
    op.drop_column('agent', 'setup_status')
    op.drop_column('agent', 'setup_result')
    op.drop_column('agent', 'check_status')
    ### end Alembic commands ###
