"""empty message

Revision ID: d511790fa384
Revises: c7f8b9624381
Create Date: 2016-04-03 22:32:27.998407

"""

# revision identifiers, used by Alembic.
revision = 'd511790fa384'
down_revision = 'c7f8b9624381'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('msg', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('task', sa.String(length=55), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.add_column(u'agent', sa.Column('crit_errs', sa.String(length=1000), nullable=False))
    op.add_column(u'agent', sa.Column('crit_errs_len', sa.Integer(), nullable=False))
    op.add_column(u'agent', sa.Column('warn_errs', sa.String(length=1000), nullable=False))
    op.add_column(u'agent', sa.Column('warn_errs_len', sa.Integer(), nullable=False))
    op.drop_column(u'agent', 'last_warn_errs')
    op.drop_column(u'agent', 'last_crit_total_errs')
    op.drop_column(u'agent', 'last_crit_errs')
    op.drop_column(u'agent', 'last_warn_total_errs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'agent', sa.Column('last_warn_total_errs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column(u'agent', sa.Column('last_crit_errs', mysql.VARCHAR(length=255), nullable=False))
    op.add_column(u'agent', sa.Column('last_crit_total_errs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column(u'agent', sa.Column('last_warn_errs', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column(u'agent', 'warn_errs_len')
    op.drop_column(u'agent', 'warn_errs')
    op.drop_column(u'agent', 'crit_errs_len')
    op.drop_column(u'agent', 'crit_errs')
    op.drop_table('alarm')
    ### end Alembic commands ###
