"""pdns

Revision ID: fb5ca267fea2
Revises: 86ba2060c277
Create Date: 2017-07-22 17:09:50.149476

"""

# revision identifiers, used by Alembic.
revision = 'fb5ca267fea2'
down_revision = '86ba2060c277'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
