# coding: utf-8


# node status
END = 0
END_MSG = 'end: {0}'
REGISTERED = 100
REGISTERED_MSG = 'registered: {0}'
START = 101
START_MSG = 'start: {0}'

# fabscript status
FABSCRIPT_END = 0
FABSCRIPT_END_MSG = 'end {0}'
FABSCRIPT_END_EMPTY_MSG = 'run empty'
FABSCRIPT_REGISTERED = 200
FABSCRIPT_REGISTERED_MSG = 'registered fabscript: {0}.{1}'
FABSCRIPT_START = 201
FABSCRIPT_START_MSG = 'start {0}'

# check status
FAILED_CHECK = 400
FAILED_CHECK_PING = 400
FAILED_CHECK_SSH = 401

# sync status
SYNC_UPDATED = 701
SYNC_CREATED = 702
SYNC_REJECTED = 710

IS_NOT_SETUPED = 400
NODE_DOES_NOT_EXIST = 401
FABSCRIPT_DOES_NOT_EXIST = 402
RESULT_DOES_NOT_EXIST = 403
