FROM centos:7

# Install
RUN yum update -y
RUN yum install -y sudo passwd openssh-server openssh-clients iproute

RUN /usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''
RUN /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''

RUN useradd {{ user }}
RUN gpasswd --add {{ user }} {{ sudo_group }}
RUN echo '{{ user }}:{{ password }}' |chpasswd

EXPOSE 22
