FROM ubuntu:14.04

# Install
RUN apt-get update -y
RUN apt-get install -y sudo passwd openssh-server

# fixed 'fatal: Missing privilege separation directory: /var/run/sshd'
RUN mkdir /var/run/sshd

RUN useradd {{ user }} -d /home/{{ user }}
RUN gpasswd --add {{ user }} {{ sudo_group }}
RUN mkdir /home/{{ user }}
RUN chown {{ user }}:{{ user }} /home/{{ user }}
RUN echo '{{ user }}:{{ password }}' |chpasswd

EXPOSE 22
