#!/bin/sh

# yum update -y
yum install -y sudo passwd openssh-server openssh-clients iproute

/usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''
/usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''

useradd {{ user }}
gpasswd --add {{ user }} wheel
gpasswd --add {{ user }} sudo
echo '{{ user }}:{{ password }}' |chpasswd

systemctl start sshd

cat << EOT > /etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
ONBOOT=yes
BOOTPROTO=none
TYPE=Ethernet
IPADDR={{ vm.ip }}
NETMASK={{ netmask }}
GATEWAY={{ gateway }}
IPV6INIT=no
EOT
systemctl restart network

sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart sshd
