#!/bin/sh

apt-get update -y
apt-get install -y sudo passwd openssh-server

# fixed 'fatal: Missing privilege separation directory: /var/run/sshd'
mkdir /var/run/sshd

echo 'fabric  ALL=(ALL:ALL) ALL' >> /etc/sudoers
echo 'hello world' > /etc/motd
useradd {{ user }} -d /home/{{ user }}
gpasswd --add {{ user }} sudo
mkdir /home/{{ user }}
chown {{ user }}:{{ user }} /home/{{ user }}
echo '{{ user }}:{{ password }}' |chpasswd

INTERFACE=`ip a | grep '2: ' | awk '{print $2}' | sed 's/:$//'`

cat << EOT > /etc/network/interfaces.d/0-${INTERFACE}.cfg
auto ${INTERFACE}
iface ${INTERFACE} inet static
    address {{ vm.ip }}
    netmask {{ netmask }}
    gateway {{ gateway }}
    nameserver {{ gateway }}
EOT

sed -i "s/.*${INTERFACE}.*//g" /etc/network/interfaces.d/*-cloud-init.cfg

ip addr flush ${INTERFACE}
service networking restart

echo "{{ vm.ip }} `hostname`" >> /etc/hosts
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
service ssh restart
