# coding: utf-8


SETUP_END = 0
START = 1
SETUP_START = 1
FABSCRIPT_REGISTERED = 2
FABSCRIPT_START = 3
FABSCRIPT_END = 4

FAILED_CHECK = 40

SYNC_UPDATED = 101
SYNC_CREATED = 102
SYNC_REJECTED = 110

IS_NOT_SETUPED = 400
NODE_DOES_NOT_EXIST = 401
FABSCRIPT_DOES_NOT_EXIST = 402
RESULT_DOES_NOT_EXIST = 403
